Adding Translation of Issue 8 for Revision
dair-ai/dair-ai.github.io pull request #59
Opened 2020-03-31 18:30 UTC by VictorGarritano

2020-03-31 19:23 UTC, fbormann requested changes
Este foi o que consegui revisar até agora, mas tá de parabéns velho, deve ter dado um trabalho da poxa.

2020-03-31 19:23 UTC, fbormann commented on _posts/2020-03-22-NLP_Newsletter[PT-BR]_8.md
> +Esse [artigo](https://arxiv.org/abs/2003.07278v1) fornece um compilado de metodologias para o aprendizado de *embeddings* contextualizados. Também estão inclusos uma revisão dos casos de uso da técni
Aqui deveria ser no singular, ao invés de "também estão inclusos" que exprime múltiplos, nós só temos uma revisão, então seria mais apropriado o uso de "Também inclui uma revisão".

2020-03-31 19:23 UTC, fbormann commented on _posts/2020-03-22-NLP_Newsletter[PT-BR]_8.md
> +O *Grand Tour* é um método linear (em contraste com outras técnicas não-lineares, como o t-SNE) que realiza a projeção de bases de dados de dimensão alta para duas dimensões. Neste novo [artigo](http
Para não fugir muito do termo utilizado no newsletter original ao invés de "comunicação entre camadas do modelo", poderíamos manter o "comunicação entre camadas da rede neural".

2020-03-31 19:23 UTC, fbormann commented on _posts/2020-03-22-NLP_Newsletter[PT-BR]_8.md
> +Um trabalho bastante interessante envolvendo pesquisadores da UC Berkeley, Google Research e da UC San Diego desenvolveu um método ([NeRF](http://www.matthewtancik.com/nerf)) para a criação de novas
Aqui "spacial location" foi traduzido como "espaço, localização" mas o termo seria melhor traduzido como "localização espacial" ou "coordenadas", não?
Outra coisa, para manter a consistência, vamos utilizar os termos em inglês ou em português porque neste resumo você utilizou "rede neural profunda" mas em outro você manteve o termo "Deep Learning". Só por motivo de que se a gente manter o mesmo termo fica até melhor de pesquisar e caminhar pelo texto depois.

2020-03-31 19:23 UTC, fbormann commented on _posts/2020-03-22-NLP_Newsletter[PT-BR]_8.md
> +Num esforço para encorajar a utilização da IA na luta contra a COVID-19, o *Allen Institute of AI* publicou o [COVID-19 Open Research Dataset (CORD-19)](https://pages.semanticscholar.org/coronavirus-
Só um pequeno erro: "A base de dados" está no singular então o correto seria "contém" ao invés de "contêm".

O final poderia ser reduzido até "coronavírus", a parte "e a doença causada por ele" não reflete o que foi escrito no texto original.

2020-03-31 19:23 UTC, fbormann commented on _posts/2020-03-22-NLP_Newsletter[PT-BR]_8.md
> +O [SECNLP](https://www.sciencedirect.com/science/article/pii/S1532046419302436) é um *survey* que inclui uma revisão detalhada de uma ampla gama de técnicas de NLP aplicadas no contexto de saúde. O t
Mesma coisa que mencionei antes, que termos vamos deixar como padrão nas traduções? Pois "survey" foi traduzido para outros termos em outras partes do texto.

2020-04-01 20:07 UTC, VictorGarritano commented on _posts/2020-03-22-NLP_Newsletter[PT-BR]_8.md
> +O [SECNLP](https://www.sciencedirect.com/science/article/pii/S1532046419302436) é um *survey* que inclui uma revisão detalhada de uma ampla gama de técnicas de NLP aplicadas no contexto de saúde. O t
Agradeço mais uma vez Felipe, vou modificar

2020-04-01 20:07 UTC, VictorGarritano commented on _posts/2020-03-22-NLP_Newsletter[PT-BR]_8.md
> +Num esforço para encorajar a utilização da IA na luta contra a COVID-19, o *Allen Institute of AI* publicou o [COVID-19 Open Research Dataset (CORD-19)](https://pages.semanticscholar.org/coronavirus-
Sim, obrigado pelas dicas, vou modificar

2020-04-01 20:09 UTC, VictorGarritano commented on _posts/2020-03-22-NLP_Newsletter[PT-BR]_8.md
> +Um trabalho bastante interessante envolvendo pesquisadores da UC Berkeley, Google Research e da UC San Diego desenvolveu um método ([NeRF](http://www.matthewtancik.com/nerf)) para a criação de novas
Sim Felipe, obrigado pela dica, vou modificar

Quanto ao uso dos termos em diversos idiomas, entendo seu ponto mas acho que não prejudica o entendimento, e eu tomei a liberdade de modificar alguns termos para tentar evitar repetições.

Bom, essa eu prefiro deixar como está, mas muito obrigado pelo comentáio

2020-04-01 20:09 UTC, VictorGarritano commented on _posts/2020-03-22-NLP_Newsletter[PT-BR]_8.md
> +O *Grand Tour* é um método linear (em contraste com outras técnicas não-lineares, como o t-SNE) que realiza a projeção de bases de dados de dimensão alta para duas dimensões. Neste novo [artigo](http
Bom, eu tomei a liberdade de utilizar termos alternativos para evitar repetições de expressões, e acredito que nesse caso a troca de termos não prejudica o entendimento.

Prefiro manter assim mesmo

2020-04-01 20:10 UTC, VictorGarritano commented on _posts/2020-03-22-NLP_Newsletter[PT-BR]_8.md
> +Esse [artigo](https://arxiv.org/abs/2003.07278v1) fornece um compilado de metodologias para o aprendizado de *embeddings* contextualizados. Também estão inclusos uma revisão dos casos de uso da técni
Oi Felipe, acho que não teve ter ficado claro pelo texto, mas aqui a minha intenção era enumerar as contrubições, que são a revisão, os métodos de compressão e as análises

Vou modificar, muito obrigado

2020-04-01 20:13 UTC, VictorGarritano commented
@omarsar I have reviewed the text, and now I think we are good to go!

@fbormann Thanks for your attention one more time!

2020-04-02 08:52 UTC, merged